# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0468f7991b9e9b96e16e5ec95621924a5325eed28ebbdd38f54603994c2638cd3181a90b364473490175dc5e0883e03bef6ceb5a7ef6bddb022cae0d425a39b

test:
  secret_key_base: a5f47a4b9e197e29cd8f29ea684b6fe7f7bacf20f7de68104e22466cfd25cb6d8078f2354ee5dd6f1c7d01cc79aca7fa667e5c54a4e039055ebe46fe98b2d1ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
